import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />
        <title>Boardy | I&apos;m the World&apos;s Most Connected AI</title>
        <meta name="description" content="This is a clone of boardy.ai" />
        <meta name="keywords" content="Next.js, React, Typescript" />
        <meta name="author" content="Christopher Leung" />
        <link
          rel="icon"
          href="https://cdn.prod.website-files.com/6705831747c825be3fbcdeeb/6712bafb9c1b788a35e55d80_Untitled%20design%20(53)%203%20(4)%20(1).png"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
